LIB_DIR	:= ./libs
WORK_DIR := ./work
REPORTS_DIR :=  $(SOCLABS_PROJECT_DIR)/imp/ASIC/nanosoc/reports
LOG_DIR := $(SOCLABS_PROJECT_DIR)/imp/ASIC/nanosoc/logs


gen_fusion_libs:
	@mkdir -p $(LIB_DIR)
	@(cd $(LIB_DIR); \
	lc_shell;)
