// Verilog-A for sar_adc, carray_8b, veriloga

`include "constants.vams"
`include "disciplines.vams"

// ------------------------------------------------------------
// Module: carray_8b
// Description:
//   8-bit binary-weighted capacitive DAC for SAR ADC.
//   Bottom plates are driven by digital control signals.
//   Top plate node: vout.
//
// Function:
//   Implements charge redistribution DAC.
//
// Assumptions:
//   - Ideal capacitors (no parasitics)
//   - No mismatch
//   - No charge injection modeled here
//
// Author: Hee
// Date: 2026-02
// ------------------------------------------------------------

module carray_8b(vtop, vbottom, vbottom_dum);
	inout vtop, vbottom_dum;
	inout [7:0] vbottom;
	electrical [7:0] vbottom; // control bus coming from the SAR FSM 
	electrical vtop, vbottom_dum;

	parameter real cu=1f from (0:inf);

	// ----------------------------------------------------------------
	// capacitor connections top plate
	// ----------------------------------------------------------------
	mim_cap_adc #(.c(1*cu)) c1 (.top(vtop), .bottom(vbottom[0]));
	mim_cap_adc #(.c(2*cu)) c2 (.top(vtop), .bottom(vbottom[1]));
	mim_cap_adc #(.c(4*cu)) c3 (.top(vtop), .bottom(vbottom[2]));
	mim_cap_adc #(.c(8*cu)) c4 (.top(vtop), .bottom(vbottom[3]));
	mim_cap_adc #(.c(16*cu)) c5 (.top(vtop), .bottom(vbottom[4]));
	mim_cap_adc #(.c(32*cu)) c6 (.top(vtop), .bottom(vbottom[5]));
	mim_cap_adc #(.c(64*cu)) c7 (.top(vtop), .bottom(vbottom[6]));
	mim_cap_adc #(.c(128*cu)) c8 (.top(vtop), .bottom(vbottom[7]));
	mim_cap_adc #(.c(1*cu)) c_dum (.top(vtop), .bottom(vbottom_dum));

/*
genvar k;

analog begin
	// --- Capacitor array top plate ---
	I(vtop,n_dummy) <+ ddt(V(vtop,n_dummy))*(1*C); 
	for (k=0; k<8; k=k+1) begin
		I(vtop,n[k]) <+ (C*(1<<k)) * ddt(V(vtop,n[k]));
	end
end
*/
endmodule
