#!/bin/bash
# Environment for the sky130 NanoSoC ASIC flow on the Cadence build machine.
# SOURCE this, do not execute it:  source setup_env.sh
#
# Everything is derived from this script's own location, so it works from any
# checkout under any user's home directory.

_SETUP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export REPO_ROOT="$(cd "$_SETUP_DIR/../../.." && pwd)"

# Genus/Innovus live in DDI221; check_cpf in 1_synthesis.tcl shells out to
# Conformal, so CONFRML241 must be on PATH too or the stage aborts (RCLP-202).
export PATH=/opt/cadence/installs/DDI221/bin:/opt/cadence/installs/CONFRML241/bin:$PATH
export CDS_LIC_FILE="${CDS_LIC_FILE:-5280@cadence.lic.sydney.edu.au}"

# soctools_flow/bin/filelist_compile.py opens sources with the locale default
# encoding; under the machine default LANG=C.UTF-8 python3.6 falls back to ASCII
# and dies on a UTF-8 BOM. Force a real UTF-8 locale.
export LC_ALL=en_US.utf8
export LANG=en_US.utf8

cd "$REPO_ROOT/nanosoc" || return 1

# nanosoc.config leaves DMA_DMA350_INCLUDE blank and the design instantiates no
# DMA-350, so skip set_env.sh's DMA configure step via its own guard file.
touch .dma350_configured

# nanosoc_tech/makefile has a hard `include $(SOCLABS_PROJECT_DIR)/autoconfig`.
# That file is in no repo and generated by nothing, so every make target dies
# without this stub. TOOL_CHAIN/SIMULATOR are used only by makefile.simulate.
[ -f autoconfig ] || printf 'TOOL_CHAIN ?= GCC\nSIMULATOR ?= xm\n' > autoconfig

# project_setup.sh recurses to $SOCLABS_DESIGN_ROOT/set_env.sh, which does not
# exist at the repo root; pre-setting it takes the other branch.
export SOCLABS_DESIGN_ROOT="$PWD"
source ./set_env.sh > /dev/null 2>&1
source ./env/dependency_env.sh

# asic_flow is a newer subtree than dependency_env.sh, which never defines this.
# The P&R stages source $SOCLABS_ASIC_FLOW_DIR/Cadence/procs.tcl.
export SOCLABS_ASIC_FLOW_DIR="$SOCLABS_PROJECT_DIR/asic_flow"

# dependency_env.sh historically defaulted ARM_IP_LIBRARY_PATH to a macOS path,
# which resolves to nothing on this machine. Genus then black-boxes every Arm
# Corstone-101 peripheral at zero area and still reports success -- that is what
# made the 2 Aug run report 8,799 instances instead of 21,192. Fall back rather
# than let it through silently.
if [ ! -d "$ARM_IP_LIBRARY_PATH/latest/Corstone-101" ]; then
    if [ -d /opt/arm/latest/Corstone-101 ]; then
        echo "NOTE: ARM_IP_LIBRARY_PATH=$ARM_IP_LIBRARY_PATH has no Corstone-101; using /opt/arm"
        export ARM_IP_LIBRARY_PATH=/opt/arm
    else
        echo "ERROR: no Corstone-101 under ARM_IP_LIBRARY_PATH=$ARM_IP_LIBRARY_PATH"
        echo "       Synthesis would silently black-box the Arm peripherals. Fix this first."
        return 1
    fi
fi

cd "$REPO_ROOT/ASIC_ours/Cadence/scripts" || return 1
echo "env ready: SOCLABS_PROJECT_DIR=$SOCLABS_PROJECT_DIR"
echo "           ARM_IP_LIBRARY_PATH=$ARM_IP_LIBRARY_PATH"
