###############################################################
#  Generated by:      Cadence Innovus 21.11-s130_1
#  OS:                Linux x86_64(Host ID srv03335)
#  Generated on:      Fri May  8 14:20:29 2026
#  Design:            nanosoc_chip_pads
#  Command:           write_io_file io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
	( topleft 
		(inst name="uPAD_CORNER_TL" orientation=R90 cell=sky130_ef_io__corner_pad)
	)
    (top
	(inst  name="uPAD_VDDIO_0"	orientation=R0	place_status=fixed )
	(inst  name="uPAD_VSSIO_0"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_VSS_0"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_VDD_0"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_02"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_03"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_04"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_05"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_06"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_07"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_08"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_09"	orientation=R0 	place_status=fixed )
	(inst  name="uPAD_P0_10"	orientation=R0 	place_status=fixed )
    )
	( bottomleft 
		(inst name="uPAD_CORNER_BL" orientation=R180 cell=sky130_ef_io__corner_pad)
	)
    (left
	(inst  name="uPAD_VDDIO_1"	orientation=R90	place_status=fixed )
	(inst  name="uPAD_VSSIO_1"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_VDD_1"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_VSS_1"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P0_15"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_00"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_01"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_02"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_03"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_04"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_05"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_06"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_07"	orientation=R90 place_status=fixed )
	(inst  name="uPAD_P1_08"	orientation=R90 place_status=fixed )
    )
	( bottomright
		(inst name="uPAD_CORNER_BR" orientation=R270 cell=sky130_ef_io__corner_pad)
	)
    (bottom
	(inst  name="uPAD_VDDIO_2"	orientation=R180 place_status=fixed )
	(inst  name="uPAD_VSSIO_2"	orientation=R180 place_status=fixed )
	(inst  name="uPAD_VDD_2"	orientation=R180 place_status=fixed )
	(inst  name="uPAD_VSS_2"	orientation=R180 place_status=fixed )
	(inst  name="uPAD_P1_11"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_P1_12"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_P1_13"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_P1_14"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_P1_15"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_SE_I"		orientation=R180	place_status=fixed )
	(inst  name="uPAD_SWDCK_I"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_SWDIO_IO"	orientation=R180	place_status=fixed )
	(inst  name="uPAD_TEST_I"	orientation=R180	place_status=fixed )
    )
	( topright 
		(inst name="uPAD_CORNER_TR" orientation=R0 cell=sky130_ef_io__corner_pad)
	)
    (right
	(inst  name="uPAD_VDDIO_3"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_VDD_3"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_VSSIO_3"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_VSS_3"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_CLK_I"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_NRST_I"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_00"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_01"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_11"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_12"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_13"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P0_14"	orientation=R270 place_status=fixed )
	(inst  name="uPAD_P1_09"	orientation=R270	place_status=fixed )
	(inst  name="uPAD_P1_10"	orientation=R270	place_status=fixed )
    )
)
