set_property PACKAGE_PIN AD28 [get_ports {UART_TX_F[2]}]
# -----------------------------------------------------------------------------
# Purpose : Main timing constraints and pin list for MPS3
# -----------------------------------------------------------------------------

####################################################################################
# Pin Assigment
####################################################################################

set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_ADDR[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {SMBF_DATA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_FIFOSEL]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nOE]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nRST]
set_property IOSTANDARD LVCMOS18 [get_ports SMBF_nWE]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_INT]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_nCS]
set_property IOSTANDARD LVCMOS18 [get_ports ETH_nOE]
set_property IOSTANDARD LVCMOS18 [get_ports USB_DACK]
set_property IOSTANDARD LVCMOS18 [get_ports USB_DREQ]
set_property IOSTANDARD LVCMOS18 [get_ports USB_INT]
set_property IOSTANDARD LVCMOS18 [get_ports USB_nCS]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CLCD_PD[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_BL]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_CS]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RD]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RS]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_RST]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TINT]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TNC]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TSCL]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_TSDA]
set_property IOSTANDARD LVCMOS18 [get_ports CLCD_WR_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nLED[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_SW[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nPB[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {USER_nPB[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CSCL]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_CSDA]
set_property IOSTANDARD LVCMOS18 [get_ports HDMI_INT]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {CS_T_D[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TCK]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TDI]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TDO]
set_property IOSTANDARD LVCMOS18 [get_ports CS_TMS]
set_property IOSTANDARD LVCMOS18 [get_ports CS_T_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CS_T_CTL]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nDET]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nSRST]
set_property IOSTANDARD LVCMOS18 [get_ports CS_nTRST]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_CK]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_CS]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_DI]
set_property IOSTANDARD LVCMOS18 [get_ports SH_ADC_DO]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_RX_F[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {UART_TX_F[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {OSCCLK[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[23]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[22]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[21]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[20]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[19]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[18]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[17]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[16]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[15]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_DATA[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {MMB_SD[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_DE]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_HS]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_IDCLK]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_SCK]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_VS]
set_property IOSTANDARD LVCMOS18 [get_ports MMB_WS]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {EMMC_DAT[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_CLK]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_CMD]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_DS]
set_property IOSTANDARD LVCMOS18 [get_ports EMMC_nRST]
# not used
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_BIDIR_P[3]}]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_BIDIR_N[3]}]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_BIDIR_P[2]}]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_BIDIR_N[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports AUD_LRCK]
set_property PACKAGE_PIN Y30 [get_ports AUD_LRCK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_MCLK]
set_property PACKAGE_PIN AB29 [get_ports AUD_MCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_nRST]
set_property PACKAGE_PIN AA27 [get_ports AUD_nRST]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SCL]
set_property PACKAGE_PIN AA28 [get_ports AUD_SCL]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SCLK]
set_property PACKAGE_PIN AB30 [get_ports AUD_SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDA]
set_property PACKAGE_PIN AA29 [get_ports AUD_SDA]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDIN]
set_property PACKAGE_PIN AA30 [get_ports AUD_SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports AUD_SDOUT]
set_property PACKAGE_PIN Y27 [get_ports AUD_SDOUT]
set_property IOSTANDARD LVCMOS33 [get_ports CB_nPOR]
set_property PACKAGE_PIN AU22 [get_ports CB_nPOR]
set_property IOSTANDARD LVCMOS33 [get_ports CB_nRST]
set_property PACKAGE_PIN AV23 [get_ports CB_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports CB_RUN]
set_property PACKAGE_PIN AR25 [get_ports CB_RUN]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_CLK]
set_property PACKAGE_PIN AT20 [get_ports CFG_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_DATAIN]
set_property PACKAGE_PIN AT19 [get_ports CFG_DATAIN]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_DATAOUT]
set_property PACKAGE_PIN AV18 [get_ports CFG_DATAOUT]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_LOAD]
set_property PACKAGE_PIN AW18 [get_ports CFG_LOAD]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_nRST]
set_property PACKAGE_PIN AR20 [get_ports CFG_nRST]
set_property IOSTANDARD LVCMOS33 [get_ports CFG_WnR]
set_property PACKAGE_PIN AT18 [get_ports CFG_WnR]
set_property PACKAGE_PIN AJ16 [get_ports CLCD_BL]
set_property PACKAGE_PIN AP15 [get_ports CLCD_CS]
set_property PACKAGE_PIN AN17 [get_ports {CLCD_PD[10]}]
set_property PACKAGE_PIN AP16 [get_ports {CLCD_PD[11]}]
set_property PACKAGE_PIN AP18 [get_ports {CLCD_PD[12]}]
set_property PACKAGE_PIN AR18 [get_ports {CLCD_PD[13]}]
set_property PACKAGE_PIN AM16 [get_ports {CLCD_PD[14]}]
set_property PACKAGE_PIN AN16 [get_ports {CLCD_PD[15]}]
set_property PACKAGE_PIN AR17 [get_ports {CLCD_PD[16]}]
set_property PACKAGE_PIN AR16 [get_ports {CLCD_PD[17]}]
set_property PACKAGE_PIN AM15 [get_ports CLCD_RD]
set_property PACKAGE_PIN AN14 [get_ports CLCD_RS]
set_property PACKAGE_PIN AK18 [get_ports CLCD_RST]
#set_property PACKAGE_PIN AN18 [get_ports CLCD_SDI]
#set_property PACKAGE_PIN AH16 [get_ports CLCD_SDO]
set_property PACKAGE_PIN AJ14 [get_ports CLCD_TINT]
set_property PACKAGE_PIN AL17 [get_ports CLCD_TNC]
set_property PACKAGE_PIN AL18 [get_ports CLCD_TSCL]
set_property PACKAGE_PIN AJ15 [get_ports CLCD_TSDA]
set_property PACKAGE_PIN AP14 [get_ports CLCD_WR_SCL]
# not used
# set_property PACKAGE_PIN N28 [get_ports {CLK_BIDIR_P[2]}]
# set_property PACKAGE_PIN N29 [get_ports {CLK_BIDIR_N[2]}]
# set_property PACKAGE_PIN E32 [get_ports {CLK_BIDIR_P[3]}]
# set_property PACKAGE_PIN D33 [get_ports {CLK_BIDIR_N[3]}]
# set_property PACKAGE_PIN G31 [get_ports {CLK_M2C_P[0]}]
# set_property PACKAGE_PIN F32 [get_ports {CLK_M2C_N[0]}]
# set_property PACKAGE_PIN E31 [get_ports {CLK_M2C_P[1]}]
# set_property PACKAGE_PIN D31 [get_ports {CLK_M2C_N[1]}]
set_property PACKAGE_PIN BB39 [get_ports CS_nDET]
set_property PACKAGE_PIN BB36 [get_ports CS_nSRST]
set_property PACKAGE_PIN BB37 [get_ports CS_nTRST]
set_property PACKAGE_PIN AW33 [get_ports CS_T_CLK]
set_property PACKAGE_PIN AY35 [get_ports CS_T_CTL]
set_property PACKAGE_PIN AW34 [get_ports {CS_T_D[0]}]
set_property PACKAGE_PIN AT34 [get_ports {CS_T_D[1]}]
set_property PACKAGE_PIN AU34 [get_ports {CS_T_D[2]}]
set_property PACKAGE_PIN AV36 [get_ports {CS_T_D[3]}]
set_property PACKAGE_PIN AW36 [get_ports {CS_T_D[4]}]
set_property PACKAGE_PIN AT35 [get_ports {CS_T_D[5]}]
set_property PACKAGE_PIN AU35 [get_ports {CS_T_D[6]}]
set_property PACKAGE_PIN AU36 [get_ports {CS_T_D[7]}]
set_property PACKAGE_PIN AV37 [get_ports {CS_T_D[8]}]
set_property PACKAGE_PIN AW35 [get_ports {CS_T_D[9]}]
set_property PACKAGE_PIN AY36 [get_ports {CS_T_D[10]}]
set_property PACKAGE_PIN AY37 [get_ports {CS_T_D[11]}]
set_property PACKAGE_PIN BB34 [get_ports {CS_T_D[12]}]
set_property PACKAGE_PIN BB35 [get_ports {CS_T_D[13]}]
set_property PACKAGE_PIN BA37 [get_ports {CS_T_D[14]}]
set_property PACKAGE_PIN BA38 [get_ports {CS_T_D[15]}]
set_property PACKAGE_PIN AV33 [get_ports CS_TCK]
set_property PACKAGE_PIN BA35 [get_ports CS_TDI]
set_property PACKAGE_PIN AW38 [get_ports CS_TDO]
set_property PACKAGE_PIN AY38 [get_ports CS_TMS]
# not used
#set_property IOSTANDARD POD12_DCI [get_ports {DDR_CHIPID[0]}]
#set_property PACKAGE_PIN J19 [get_ports {DDR_CHIPID[0]}]
#set_property IOSTANDARD POD12_DCI [get_ports {DDR_CHIPID[1]}]
#set_property PACKAGE_PIN G20 [get_ports {DDR_CHIPID[1]}]
#set_property IOSTANDARD POD12_DCI [get_ports DDR_nALERT]
#set_property PACKAGE_PIN P15 [get_ports DDR_nALERT]
#set_property IOSTANDARD POD12_DCI [get_ports DDR_nEVENT]
#set_property PACKAGE_PIN C17 [get_ports DDR_nEVENT]
# set_property IOSTANDARD POD12_DCI [get_ports DDR_PARITY]
# set_property PACKAGE_PIN D18 [get_ports DDR_PARITY]
# set_property IOSTANDARD POD12_DCI [get_ports DDR_SCL]
# set_property PACKAGE_PIN N21 [get_ports DDR_SCL]
# set_property IOSTANDARD POD12_DCI [get_ports DDR_SDA]
# set_property PACKAGE_PIN P21 [get_ports DDR_SDA]
# set_property PACKAGE_PIN AC42 [get_ports {DP_M2C_N[0]}]
# set_property PACKAGE_PIN AJ42 [get_ports {DP_M2C_N[1]}]
# set_property PACKAGE_PIN AE42 [get_ports {DP_M2C_N[2]}]
# set_property PACKAGE_PIN W42 [get_ports {DP_M2C_N[3]}]
# set_property PACKAGE_PIN R42 [get_ports {DP_M2C_N[4]}]
# set_property PACKAGE_PIN L42 [get_ports {DP_M2C_N[5]}]
# set_property PACKAGE_PIN N42 [get_ports {DP_M2C_N[6]}]
# set_property PACKAGE_PIN U42 [get_ports {DP_M2C_N[7]}]
# set_property PACKAGE_PIN AA42 [get_ports {DP_M2C_N[8]}]
# set_property PACKAGE_PIN AG42 [get_ports {DP_M2C_N[9]}]
# set_property PACKAGE_PIN AC41 [get_ports {DP_M2C_P[0]}]
# set_property PACKAGE_PIN AJ41 [get_ports {DP_M2C_P[1]}]
# set_property PACKAGE_PIN AE41 [get_ports {DP_M2C_P[2]}]
# set_property PACKAGE_PIN W41 [get_ports {DP_M2C_P[3]}]
# set_property PACKAGE_PIN R41 [get_ports {DP_M2C_P[4]}]
# set_property PACKAGE_PIN L41 [get_ports {DP_M2C_P[5]}]
# set_property PACKAGE_PIN N41 [get_ports {DP_M2C_P[6]}]
# set_property PACKAGE_PIN U41 [get_ports {DP_M2C_P[7]}]
# set_property PACKAGE_PIN AA41 [get_ports {DP_M2C_P[8]}]
# set_property PACKAGE_PIN AG41 [get_ports {DP_M2C_P[9]}]
set_property PACKAGE_PIN AG34 [get_ports HDMI_CSCL]
set_property PACKAGE_PIN AE33 [get_ports HDMI_CSDA]
set_property PACKAGE_PIN AF33 [get_ports HDMI_INT]
set_property PACKAGE_PIN W29 [get_ports EMMC_CLK]
set_property PACKAGE_PIN AC34 [get_ports EMMC_CMD]
set_property PACKAGE_PIN Y32 [get_ports {EMMC_DAT[0]}]
set_property PACKAGE_PIN Y33 [get_ports {EMMC_DAT[1]}]
set_property PACKAGE_PIN W33 [get_ports {EMMC_DAT[2]}]
set_property PACKAGE_PIN W34 [get_ports {EMMC_DAT[3]}]
set_property PACKAGE_PIN AA34 [get_ports {EMMC_DAT[4]}]
set_property PACKAGE_PIN AB34 [get_ports {EMMC_DAT[5]}]
set_property PACKAGE_PIN W31 [get_ports {EMMC_DAT[6]}]
set_property PACKAGE_PIN Y31 [get_ports {EMMC_DAT[7]}]
set_property PACKAGE_PIN AE32 [get_ports EMMC_DS]
set_property PACKAGE_PIN W30 [get_ports EMMC_nRST]
set_property PACKAGE_PIN AK23 [get_ports ETH_INT]
set_property PACKAGE_PIN AL24 [get_ports ETH_nCS]
set_property PACKAGE_PIN AJ23 [get_ports ETH_nOE]
# not used
# set_property PACKAGE_PIN AV38 [get_ports FMC_CLK_DIR]
# set_property PACKAGE_PIN AL42 [get_ports FMC_nPRSNT]
# set_property PACKAGE_PIN BB40 [get_ports {HA_N[2]}]
# set_property PACKAGE_PIN BA41 [get_ports {HA_N[3]}]
# set_property PACKAGE_PIN AY40 [get_ports {HA_N[4]}]
# set_property PACKAGE_PIN AU42 [get_ports {HA_N[5]}]
# set_property PACKAGE_PIN AY42 [get_ports {HA_N[6]}]
# set_property PACKAGE_PIN AW41 [get_ports {HA_N[7]}]
# set_property PACKAGE_PIN AU37 [get_ports {HA_N[8]}]
# set_property PACKAGE_PIN AT42 [get_ports {HA_N[9]}]
# set_property PACKAGE_PIN AT38 [get_ports {HA_N[10]}]
# set_property PACKAGE_PIN AV42 [get_ports {HA_N[11]}]
# set_property PACKAGE_PIN AR37 [get_ports {HA_N[12]}]
# set_property PACKAGE_PIN AN42 [get_ports {HA_N[13]}]
# set_property PACKAGE_PIN AP38 [get_ports {HA_N[14]}]
# set_property PACKAGE_PIN AN37 [get_ports {HA_N[15]}]
# set_property PACKAGE_PIN AM42 [get_ports {HA_N[16]}]
# set_property PACKAGE_PIN AR41 [get_ports {HA_N[18]}]
# set_property PACKAGE_PIN AM39 [get_ports {HA_N[19]}]
# set_property PACKAGE_PIN AR40 [get_ports {HA_N[20]}]
# set_property PACKAGE_PIN AM40 [get_ports {HA_N[21]}]
# set_property PACKAGE_PIN AK38 [get_ports {HA_N[22]}]
# set_property PACKAGE_PIN AL38 [get_ports {HA_N[23]}]
# set_property PACKAGE_PIN AT39 [get_ports {HA_P[0]}]
# set_property PACKAGE_PIN AT40 [get_ports {HA_N[0]}]
# set_property PACKAGE_PIN AU39 [get_ports {HA_P[1]}]
# set_property PACKAGE_PIN AU40 [get_ports {HA_N[1]}]
# set_property PACKAGE_PIN BA39 [get_ports {HA_P[2]}]
# set_property PACKAGE_PIN BA40 [get_ports {HA_P[3]}]
# set_property PACKAGE_PIN AW39 [get_ports {HA_P[4]}]
# set_property PACKAGE_PIN AU41 [get_ports {HA_P[5]}]
# set_property PACKAGE_PIN AY41 [get_ports {HA_P[6]}]
# set_property PACKAGE_PIN AW40 [get_ports {HA_P[7]}]
# set_property PACKAGE_PIN AT37 [get_ports {HA_P[8]}]
# set_property PACKAGE_PIN AR42 [get_ports {HA_P[9]}]
# set_property PACKAGE_PIN AR38 [get_ports {HA_P[10]}]
# set_property PACKAGE_PIN AV41 [get_ports {HA_P[11]}]
# set_property PACKAGE_PIN AR36 [get_ports {HA_P[12]}]
# set_property PACKAGE_PIN AN41 [get_ports {HA_P[13]}]
# set_property PACKAGE_PIN AN38 [get_ports {HA_P[14]}]
# set_property PACKAGE_PIN AM37 [get_ports {HA_P[15]}]
# set_property PACKAGE_PIN AM41 [get_ports {HA_P[16]}]
# set_property PACKAGE_PIN AN39 [get_ports {HA_P[17]}]
# set_property PACKAGE_PIN AP39 [get_ports {HA_N[17]}]
# set_property PACKAGE_PIN AP41 [get_ports {HA_P[18]}]
# set_property PACKAGE_PIN AL39 [get_ports {HA_P[19]}]
# set_property PACKAGE_PIN AP40 [get_ports {HA_P[20]}]
# set_property PACKAGE_PIN AL40 [get_ports {HA_P[21]}]
# set_property PACKAGE_PIN AK37 [get_ports {HA_P[22]}]
# set_property PACKAGE_PIN AL37 [get_ports {HA_P[23]}]
# set_property PACKAGE_PIN T32 [get_ports {HB_N[1]}]
# set_property PACKAGE_PIN V33 [get_ports {HB_N[2]}]
# set_property PACKAGE_PIN V29 [get_ports {HB_N[3]}]
# set_property PACKAGE_PIN T30 [get_ports {HB_N[4]}]
# set_property PACKAGE_PIN T34 [get_ports {HB_N[5]}]
# set_property PACKAGE_PIN R32 [get_ports {HB_N[7]}]
# set_property PACKAGE_PIN P29 [get_ports {HB_N[8]}]
# set_property PACKAGE_PIN P30 [get_ports {HB_N[9]}]
# set_property PACKAGE_PIN K28 [get_ports {HB_N[10]}]
# set_property PACKAGE_PIN L29 [get_ports {HB_N[11]}]
# set_property PACKAGE_PIN K31 [get_ports {HB_N[12]}]
# set_property PACKAGE_PIN L33 [get_ports {HB_N[13]}]
# set_property PACKAGE_PIN U31 [get_ports {HB_N[14]}]
# set_property PACKAGE_PIN N33 [get_ports {HB_N[15]}]
# set_property PACKAGE_PIN L34 [get_ports {HB_N[16]}]
# set_property PACKAGE_PIN R28 [get_ports {HB_N[18]}]
# set_property PACKAGE_PIN N27 [get_ports {HB_N[19]}]
# set_property PACKAGE_PIN U34 [get_ports {HB_N[20]}]
# set_property PACKAGE_PIN N34 [get_ports {HB_N[21]}]
# set_property PACKAGE_PIN N31 [get_ports {HB_P[0]}]
# set_property PACKAGE_PIN M31 [get_ports {HB_N[0]}]
# set_property PACKAGE_PIN U32 [get_ports {HB_P[1]}]
# set_property PACKAGE_PIN V32 [get_ports {HB_P[2]}]
# set_property PACKAGE_PIN V28 [get_ports {HB_P[3]}]
# set_property PACKAGE_PIN U30 [get_ports {HB_P[4]}]
# set_property PACKAGE_PIN T33 [get_ports {HB_P[5]}]
# set_property PACKAGE_PIN M30 [get_ports {HB_P[6]}]
# set_property PACKAGE_PIN L30 [get_ports {HB_N[6]}]
# set_property PACKAGE_PIN R31 [get_ports {HB_P[7]}]
# set_property PACKAGE_PIN P28 [get_ports {HB_P[8]}]
# set_property PACKAGE_PIN R30 [get_ports {HB_P[9]}]
# set_property PACKAGE_PIN L28 [get_ports {HB_P[10]}]
# set_property PACKAGE_PIN M29 [get_ports {HB_P[11]}]
# set_property PACKAGE_PIN K30 [get_ports {HB_P[12]}]
# set_property PACKAGE_PIN L32 [get_ports {HB_P[13]}]
# set_property PACKAGE_PIN V31 [get_ports {HB_P[14]}]
# set_property PACKAGE_PIN P33 [get_ports {HB_P[15]}]
# set_property PACKAGE_PIN M34 [get_ports {HB_P[16]}]
# set_property PACKAGE_PIN N32 [get_ports {HB_P[17]}]
# set_property PACKAGE_PIN M32 [get_ports {HB_N[17]}]
# set_property PACKAGE_PIN T28 [get_ports {HB_P[18]}]
# set_property PACKAGE_PIN N26 [get_ports {HB_P[19]}]
# set_property PACKAGE_PIN V34 [get_ports {HB_P[20]}]
# set_property PACKAGE_PIN P34 [get_ports {HB_P[21]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {CLK_CFG}]
# set_property PACKAGE_PIN AT27 [get_ports {CLK_CFG}]
# set_property IOSTANDARD LVCMOS33 [get_ports {IOFPGA_CSIB}]
# set_property PACKAGE_PIN BA27 [get_ports {IOFPGA_CSIB}]
# set_property IOSTANDARD LVCMOS33 [get_ports {IOFPGA_D[4]}]
# set_property PACKAGE_PIN AV26 [get_ports {IOFPGA_D[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {IOFPGA_D[5]}]
# set_property PACKAGE_PIN AV27 [get_ports {IOFPGA_D[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {IOFPGA_D[6]}]
# set_property PACKAGE_PIN AU29 [get_ports {IOFPGA_D[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {IOFPGA_D[7]}]
# set_property PACKAGE_PIN AV29 [get_ports {IOFPGA_D[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports IOFPGA_NRST]
set_property PACKAGE_PIN AV31 [get_ports IOFPGA_NRST]
set_property IOSTANDARD LVCMOS18 [get_ports IOFPGA_NSPIR]
set_property PACKAGE_PIN AV32 [get_ports IOFPGA_NSPIR]
set_property IOSTANDARD LVCMOS33 [get_ports IOFPGA_SYSWDT]
set_property PACKAGE_PIN AU20 [get_ports IOFPGA_SYSWDT]
# not used
# set_property PACKAGE_PIN AN27 [get_ports {LA_N[2]}]
# set_property PACKAGE_PIN AP30 [get_ports {LA_N[3]}]
# set_property PACKAGE_PIN AN29 [get_ports {LA_N[4]}]
# set_property PACKAGE_PIN AR35 [get_ports {LA_N[5]}]
# set_property PACKAGE_PIN AR33 [get_ports {LA_N[6]}]
# set_property PACKAGE_PIN AN32 [get_ports {LA_N[7]}]
# set_property PACKAGE_PIN AP31 [get_ports {LA_N[8]}]
# set_property PACKAGE_PIN AN34 [get_ports {LA_N[9]}]
# set_property PACKAGE_PIN AL35 [get_ports {LA_N[10]}]
# set_property PACKAGE_PIN AM36 [get_ports {LA_N[11]}]
# set_property PACKAGE_PIN AP34 [get_ports {LA_N[12]}]
# set_property PACKAGE_PIN AL32 [get_ports {LA_N[13]}]
# set_property PACKAGE_PIN AK36 [get_ports {LA_N[14]}]
# set_property PACKAGE_PIN AJ34 [get_ports {LA_N[15]}]
# set_property PACKAGE_PIN AL33 [get_ports {LA_N[16]}]
# set_property PACKAGE_PIN AJ29 [get_ports {LA_N[19]}]
# set_property PACKAGE_PIN AJ33 [get_ports {LA_N[20]}]
# set_property PACKAGE_PIN AH29 [get_ports {LA_N[21]}]
# set_property PACKAGE_PIN AH31 [get_ports {LA_N[22]}]
# set_property PACKAGE_PIN AG30 [get_ports {LA_N[23]}]
# set_property PACKAGE_PIN G32 [get_ports {LA_N[24]}]
# set_property PACKAGE_PIN H34 [get_ports {LA_N[25]}]
# set_property PACKAGE_PIN H31 [get_ports {LA_N[26]}]
# set_property PACKAGE_PIN K33 [get_ports {LA_N[27]}]
# set_property PACKAGE_PIN H29 [get_ports {LA_N[28]}]
# set_property PACKAGE_PIN H33 [get_ports {LA_N[29]}]
# set_property PACKAGE_PIN F34 [get_ports {LA_N[30]}]
# set_property PACKAGE_PIN E33 [get_ports {LA_N[31]}]
# set_property PACKAGE_PIN C34 [get_ports {LA_N[32]}]
# set_property PACKAGE_PIN G30 [get_ports {LA_N[33]}]
# set_property PACKAGE_PIN AM29 [get_ports {LA_P[0]}]
# set_property PACKAGE_PIN AM30 [get_ports {LA_N[0]}]
# set_property PACKAGE_PIN AL29 [get_ports {LA_P[1]}]
# set_property PACKAGE_PIN AL30 [get_ports {LA_N[1]}]
# set_property PACKAGE_PIN AM27 [get_ports {LA_P[2]}]
# set_property PACKAGE_PIN AP29 [get_ports {LA_P[3]}]
# set_property PACKAGE_PIN AN28 [get_ports {LA_P[4]}]
# set_property PACKAGE_PIN AP35 [get_ports {LA_P[5]}]
# set_property PACKAGE_PIN AP33 [get_ports {LA_P[6]}]
# set_property PACKAGE_PIN AM32 [get_ports {LA_P[7]}]
# set_property PACKAGE_PIN AN31 [get_ports {LA_P[8]}]
# set_property PACKAGE_PIN AM34 [get_ports {LA_P[9]}]
# set_property PACKAGE_PIN AL34 [get_ports {LA_P[10]}]
# set_property PACKAGE_PIN AM35 [get_ports {LA_P[11]}]
# set_property PACKAGE_PIN AN33 [get_ports {LA_P[12]}]
# set_property PACKAGE_PIN AK32 [get_ports {LA_P[13]}]
# set_property PACKAGE_PIN AK35 [get_ports {LA_P[14]}]
# set_property PACKAGE_PIN AH34 [get_ports {LA_P[15]}]
# set_property PACKAGE_PIN AK33 [get_ports {LA_P[16]}]
# set_property PACKAGE_PIN AK30 [get_ports {LA_P[17]}]
# set_property PACKAGE_PIN AK31 [get_ports {LA_N[17]}]
# set_property PACKAGE_PIN AJ30 [get_ports {LA_P[18]}]
# set_property PACKAGE_PIN AJ31 [get_ports {LA_N[18]}]
# set_property PACKAGE_PIN AJ28 [get_ports {LA_P[19]}]
# set_property PACKAGE_PIN AH33 [get_ports {LA_P[20]}]
# set_property PACKAGE_PIN AH28 [get_ports {LA_P[21]}]
# set_property PACKAGE_PIN AG31 [get_ports {LA_P[22]}]
# set_property PACKAGE_PIN AG29 [get_ports {LA_P[23]}]
# set_property PACKAGE_PIN H32 [get_ports {LA_P[24]}]
# set_property PACKAGE_PIN J34 [get_ports {LA_P[25]}]
# set_property PACKAGE_PIN J30 [get_ports {LA_P[26]}]
# set_property PACKAGE_PIN K32 [get_ports {LA_P[27]}]
# set_property PACKAGE_PIN J29 [get_ports {LA_P[28]}]
# set_property PACKAGE_PIN J33 [get_ports {LA_P[29]}]
# set_property PACKAGE_PIN G34 [get_ports {LA_P[30]}]
# set_property PACKAGE_PIN F33 [get_ports {LA_P[31]}]
# set_property PACKAGE_PIN D34 [get_ports {LA_P[32]}]
# set_property PACKAGE_PIN G29 [get_ports {LA_P[33]}]
set_property PACKAGE_PIN AM17 [get_ports {MMB_DATA[0]}]
set_property PACKAGE_PIN AL14 [get_ports {MMB_DATA[1]}]
set_property PACKAGE_PIN AK15 [get_ports {MMB_DATA[2]}]
set_property PACKAGE_PIN AK17 [get_ports {MMB_DATA[3]}]
set_property PACKAGE_PIN AM14 [get_ports {MMB_DATA[4]}]
set_property PACKAGE_PIN AN13 [get_ports {MMB_DATA[5]}]
set_property PACKAGE_PIN AM11 [get_ports {MMB_DATA[6]}]
set_property PACKAGE_PIN AN11 [get_ports {MMB_DATA[7]}]
set_property PACKAGE_PIN AR13 [get_ports {MMB_DATA[8]}]
set_property PACKAGE_PIN AR12 [get_ports {MMB_DATA[9]}]
set_property PACKAGE_PIN AL10 [get_ports {MMB_DATA[10]}]
set_property PACKAGE_PIN AM10 [get_ports {MMB_DATA[11]}]
set_property PACKAGE_PIN AM12 [get_ports {MMB_DATA[12]}]
set_property PACKAGE_PIN AN12 [get_ports {MMB_DATA[13]}]
set_property PACKAGE_PIN AP13 [get_ports {MMB_DATA[14]}]
set_property PACKAGE_PIN AK13 [get_ports {MMB_DATA[15]}]
set_property PACKAGE_PIN AK12 [get_ports {MMB_DATA[16]}]
set_property PACKAGE_PIN AK11 [get_ports {MMB_DATA[17]}]
set_property PACKAGE_PIN AK10 [get_ports {MMB_DATA[18]}]
set_property PACKAGE_PIN AH13 [get_ports {MMB_DATA[19]}]
set_property PACKAGE_PIN AJ13 [get_ports {MMB_DATA[20]}]
set_property PACKAGE_PIN AJ11 [get_ports {MMB_DATA[21]}]
set_property PACKAGE_PIN AJ10 [get_ports {MMB_DATA[22]}]
set_property PACKAGE_PIN AH12 [get_ports {MMB_DATA[23]}]
set_property PACKAGE_PIN AH11 [get_ports MMB_DE]
set_property PACKAGE_PIN AG12 [get_ports MMB_HS]
set_property PACKAGE_PIN AH14 [get_ports MMB_IDCLK]
set_property PACKAGE_PIN AF29 [get_ports MMB_SCK]
set_property PACKAGE_PIN AC28 [get_ports {MMB_SD[0]}]
set_property PACKAGE_PIN AC29 [get_ports {MMB_SD[1]}]
set_property PACKAGE_PIN AE27 [get_ports {MMB_SD[2]}]
set_property PACKAGE_PIN AF34 [get_ports {MMB_SD[3]}]
set_property PACKAGE_PIN AG11 [get_ports MMB_VS]
set_property PACKAGE_PIN AF30 [get_ports MMB_WS]
set_property PACKAGE_PIN AL15 [get_ports {OSCCLK[0]}]
set_property PACKAGE_PIN AK16 [get_ports {OSCCLK[1]}]
set_property PACKAGE_PIN AY32 [get_ports {OSCCLK[2]}]
set_property PACKAGE_PIN AY30 [get_ports {OSCCLK[3]}]
set_property PACKAGE_PIN AC31 [get_ports {OSCCLK[4]}]
set_property PACKAGE_PIN AC32 [get_ports {OSCCLK[5]}]
set_property PACKAGE_PIN AT29 [get_ports PB_IRQ]

set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D0]
set_property PACKAGE_PIN AU24 [get_ports QSPI_D0]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D1]
set_property PACKAGE_PIN AV24 [get_ports QSPI_D1]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D2]
set_property PACKAGE_PIN AV21 [get_ports QSPI_D2]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_D3]
set_property PACKAGE_PIN AV22 [get_ports QSPI_D3]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_nCS]
set_property PACKAGE_PIN AT24 [get_ports QSPI_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports QSPI_SCLK]
set_property PACKAGE_PIN AT25 [get_ports QSPI_SCLK]
# not used
# set_property PACKAGE_PIN AL13 [get_ports SATA_CLK_P]
# set_property PACKAGE_PIN AL12 [get_ports SATA_CLK_N]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[0]}]
set_property PACKAGE_PIN AW14 [get_ports {SH0_IO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[1]}]
set_property PACKAGE_PIN AW13 [get_ports {SH0_IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[2]}]
set_property PACKAGE_PIN AW15 [get_ports {SH0_IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[3]}]
set_property PACKAGE_PIN AY15 [get_ports {SH0_IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[4]}]
set_property PACKAGE_PIN AY13 [get_ports {SH0_IO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[5]}]
set_property PACKAGE_PIN AY12 [get_ports {SH0_IO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[6]}]
set_property PACKAGE_PIN BA15 [get_ports {SH0_IO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[7]}]
set_property PACKAGE_PIN BB14 [get_ports {SH0_IO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[8]}]
set_property PACKAGE_PIN BA12 [get_ports {SH0_IO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[9]}]
set_property PACKAGE_PIN BB12 [get_ports {SH0_IO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[10]}]
set_property PACKAGE_PIN BA14 [get_ports {SH0_IO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[11]}]
set_property PACKAGE_PIN BA13 [get_ports {SH0_IO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[12]}]
set_property PACKAGE_PIN BB15 [get_ports {SH0_IO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[13]}]
set_property PACKAGE_PIN AU12 [get_ports {SH0_IO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[14]}]
set_property PACKAGE_PIN AV12 [get_ports {SH0_IO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[15]}]
set_property PACKAGE_PIN AV17 [get_ports {SH0_IO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[16]}]
set_property PACKAGE_PIN AV16 [get_ports {SH0_IO[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH0_IO[17]}]
set_property PACKAGE_PIN AT14 [get_ports {SH0_IO[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[0]}]
set_property PACKAGE_PIN AT17 [get_ports {SH1_IO[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[1]}]
set_property PACKAGE_PIN AU17 [get_ports {SH1_IO[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[2]}]
set_property PACKAGE_PIN AV19 [get_ports {SH1_IO[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[3]}]
set_property PACKAGE_PIN AW19 [get_ports {SH1_IO[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[4]}]
set_property PACKAGE_PIN AW20 [get_ports {SH1_IO[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[5]}]
set_property PACKAGE_PIN BA19 [get_ports {SH1_IO[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[6]}]
set_property PACKAGE_PIN BA18 [get_ports {SH1_IO[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[7]}]
set_property PACKAGE_PIN AY20 [get_ports {SH1_IO[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[8]}]
set_property PACKAGE_PIN BA20 [get_ports {SH1_IO[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[9]}]
set_property PACKAGE_PIN BA17 [get_ports {SH1_IO[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[10]}]
set_property PACKAGE_PIN BB17 [get_ports {SH1_IO[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[11]}]
set_property PACKAGE_PIN BB20 [get_ports {SH1_IO[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[12]}]
set_property PACKAGE_PIN BB19 [get_ports {SH1_IO[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[13]}]
set_property PACKAGE_PIN AW16 [get_ports {SH1_IO[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[14]}]
set_property PACKAGE_PIN AY16 [get_ports {SH1_IO[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[15]}]
set_property PACKAGE_PIN AY18 [get_ports {SH1_IO[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[16]}]
set_property PACKAGE_PIN AY17 [get_ports {SH1_IO[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SH1_IO[17]}]
set_property PACKAGE_PIN BB16 [get_ports {SH1_IO[17]}]
set_property PACKAGE_PIN AL25 [get_ports SH_ADC_CK]
set_property PACKAGE_PIN AM25 [get_ports SH_ADC_CS]
set_property PACKAGE_PIN AP25 [get_ports SH_ADC_DI]
set_property PACKAGE_PIN AP26 [get_ports SH_ADC_DO]
set_property IOSTANDARD LVCMOS33 [get_ports SH_nRST]
set_property PACKAGE_PIN AU14 [get_ports SH_nRST]
set_property PACKAGE_PIN AK20 [get_ports {SMBF_ADDR[0]}]
set_property PACKAGE_PIN AK21 [get_ports {SMBF_ADDR[1]}]
set_property PACKAGE_PIN AJ18 [get_ports {SMBF_ADDR[2]}]
set_property PACKAGE_PIN AJ19 [get_ports {SMBF_ADDR[3]}]
set_property PACKAGE_PIN AH21 [get_ports {SMBF_ADDR[4]}]
set_property PACKAGE_PIN AJ21 [get_ports {SMBF_ADDR[5]}]
set_property PACKAGE_PIN AH19 [get_ports {SMBF_ADDR[6]}]
set_property PACKAGE_PIN AK22 [get_ports {SMBF_DATA[0]}]
set_property PACKAGE_PIN AL22 [get_ports {SMBF_DATA[1]}]
set_property PACKAGE_PIN AL19 [get_ports {SMBF_DATA[2]}]
set_property PACKAGE_PIN AL20 [get_ports {SMBF_DATA[3]}]
set_property PACKAGE_PIN AH18 [get_ports {SMBF_DATA[4]}]
set_property PACKAGE_PIN AM19 [get_ports {SMBF_DATA[5]}]
set_property PACKAGE_PIN AN19 [get_ports {SMBF_DATA[6]}]
set_property PACKAGE_PIN AP19 [get_ports {SMBF_DATA[7]}]
set_property PACKAGE_PIN AP20 [get_ports {SMBF_DATA[8]}]
set_property PACKAGE_PIN AM20 [get_ports {SMBF_DATA[9]}]
set_property PACKAGE_PIN AN21 [get_ports {SMBF_DATA[10]}]
set_property PACKAGE_PIN AP21 [get_ports {SMBF_DATA[11]}]
set_property PACKAGE_PIN AR22 [get_ports {SMBF_DATA[12]}]
set_property PACKAGE_PIN AM21 [get_ports {SMBF_DATA[13]}]
set_property PACKAGE_PIN AM22 [get_ports {SMBF_DATA[14]}]
set_property PACKAGE_PIN AN22 [get_ports {SMBF_DATA[15]}]
set_property PACKAGE_PIN AJ20 [get_ports SMBF_FIFOSEL]
set_property PACKAGE_PIN AN23 [get_ports SMBF_nOE]
set_property PACKAGE_PIN AL23 [get_ports SMBF_nRST]
set_property PACKAGE_PIN AP23 [get_ports SMBF_nWE]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[16]}]
set_property PACKAGE_PIN AR26 [get_ports {SMBM_A[16]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[17]}]
set_property PACKAGE_PIN AT22 [get_ports {SMBM_A[17]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[18]}]
set_property PACKAGE_PIN AT23 [get_ports {SMBM_A[18]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[19]}]
set_property PACKAGE_PIN AU21 [get_ports {SMBM_A[19]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[20]}]
set_property PACKAGE_PIN AY22 [get_ports {SMBM_A[20]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[21]}]
set_property PACKAGE_PIN BA22 [get_ports {SMBM_A[21]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[22]}]
set_property PACKAGE_PIN AW21 [get_ports {SMBM_A[22]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[23]}]
set_property PACKAGE_PIN AY21 [get_ports {SMBM_A[23]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[24]}]
set_property PACKAGE_PIN BA23 [get_ports {SMBM_A[24]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_A[25]}]
set_property PACKAGE_PIN BA24 [get_ports {SMBM_A[25]}]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_CLK]
set_property PACKAGE_PIN AY25 [get_ports SMBM_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[0]}]
set_property PACKAGE_PIN BB21 [get_ports {SMBM_D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[1]}]
set_property PACKAGE_PIN BB22 [get_ports {SMBM_D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[2]}]
set_property PACKAGE_PIN AW24 [get_ports {SMBM_D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[3]}]
set_property PACKAGE_PIN AW25 [get_ports {SMBM_D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[4]}]
set_property PACKAGE_PIN AW23 [get_ports {SMBM_D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[5]}]
set_property PACKAGE_PIN AY23 [get_ports {SMBM_D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[6]}]
set_property PACKAGE_PIN BB24 [get_ports {SMBM_D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[7]}]
set_property PACKAGE_PIN AY27 [get_ports {SMBM_D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[8]}]
set_property PACKAGE_PIN AY26 [get_ports {SMBM_D[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[9]}]
set_property PACKAGE_PIN AY28 [get_ports {SMBM_D[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[10]}]
set_property PACKAGE_PIN BA28 [get_ports {SMBM_D[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[11]}]
set_property PACKAGE_PIN BA25 [get_ports {SMBM_D[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[12]}]
set_property PACKAGE_PIN BB25 [get_ports {SMBM_D[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[13]}]
set_property PACKAGE_PIN AW28 [get_ports {SMBM_D[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[14]}]
set_property PACKAGE_PIN AW29 [get_ports {SMBM_D[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_D[15]}]
set_property PACKAGE_PIN BB26 [get_ports {SMBM_D[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nBL[0]}]
set_property PACKAGE_PIN AU26 [get_ports {SMBM_nBL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nBL[1]}]
set_property PACKAGE_PIN AR28 [get_ports {SMBM_nBL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[1]}]
set_property PACKAGE_PIN BB27 [get_ports {SMBM_nE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[2]}]
set_property PACKAGE_PIN AU27 [get_ports {SMBM_nE[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[3]}]
set_property PACKAGE_PIN AV28 [get_ports {SMBM_nE[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SMBM_nE[4]}]
set_property PACKAGE_PIN AU25 [get_ports {SMBM_nE[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nOE]
set_property PACKAGE_PIN AT28 [get_ports SMBM_nOE]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nWAIT]
set_property PACKAGE_PIN AP28 [get_ports SMBM_nWAIT]
set_property IOSTANDARD LVCMOS33 [get_ports SMBM_nWE]
set_property PACKAGE_PIN AR27 [get_ports SMBM_nWE]
set_property PACKAGE_PIN AF28 [get_ports {UART_RX_F[0]}]
set_property PACKAGE_PIN AE31 [get_ports {UART_RX_F[1]}]
set_property PACKAGE_PIN AE28 [get_ports {UART_RX_F[2]}]
set_property PACKAGE_PIN AD30 [get_ports {UART_RX_F[3]}]
set_property PACKAGE_PIN AF27 [get_ports {UART_TX_F[0]}]
set_property PACKAGE_PIN AE30 [get_ports {UART_TX_F[1]}]
set_property PACKAGE_PIN AD29 [get_ports {UART_TX_F[3]}]
set_property PACKAGE_PIN AN26 [get_ports USB_DACK]
set_property PACKAGE_PIN AN24 [get_ports USB_DREQ]
set_property PACKAGE_PIN AP24 [get_ports USB_INT]
set_property PACKAGE_PIN AM26 [get_ports USB_nCS]
set_property IOSTANDARD LVCMOS33 [get_ports USD_CLK]
set_property PACKAGE_PIN AU15 [get_ports USD_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports USD_CMD]
set_property PACKAGE_PIN AU16 [get_ports USD_CMD]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[0]}]
set_property PACKAGE_PIN AV14 [get_ports {USD_DAT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[1]}]
set_property PACKAGE_PIN AV13 [get_ports {USD_DAT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[2]}]
set_property PACKAGE_PIN AT13 [get_ports {USD_DAT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {USD_DAT[3]}]
set_property PACKAGE_PIN AT12 [get_ports {USD_DAT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports USD_NCD]
set_property PACKAGE_PIN AT15 [get_ports USD_NCD]
set_property PACKAGE_PIN AU32 [get_ports {USER_nLED[0]}]
set_property PACKAGE_PIN AU30 [get_ports {USER_nLED[1]}]
set_property PACKAGE_PIN AU31 [get_ports {USER_nLED[2]}]
set_property PACKAGE_PIN AR32 [get_ports {USER_nLED[3]}]
set_property PACKAGE_PIN AT33 [get_ports {USER_nLED[4]}]
set_property PACKAGE_PIN AW30 [get_ports {USER_nLED[5]}]
set_property PACKAGE_PIN AW31 [get_ports {USER_nLED[6]}]
set_property PACKAGE_PIN AR30 [get_ports {USER_nLED[7]}]
set_property PACKAGE_PIN BB31 [get_ports {USER_nLED[8]}]
set_property PACKAGE_PIN BB32 [get_ports {USER_nLED[9]}]
set_property PACKAGE_PIN AT30 [get_ports {USER_nPB[0]}]
set_property PACKAGE_PIN AT32 [get_ports {USER_nPB[1]}]
set_property PACKAGE_PIN BA29 [get_ports {USER_SW[0]}]
set_property PACKAGE_PIN BB29 [get_ports {USER_SW[1]}]
set_property PACKAGE_PIN BA32 [get_ports {USER_SW[2]}]
set_property PACKAGE_PIN BA33 [get_ports {USER_SW[3]}]
set_property PACKAGE_PIN BA30 [get_ports {USER_SW[4]}]
set_property PACKAGE_PIN BB30 [get_ports {USER_SW[5]}]
set_property PACKAGE_PIN AY33 [get_ports {USER_SW[6]}]
set_property PACKAGE_PIN AY31 [get_ports {USER_SW[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports WDOG_RREQ]
set_property PACKAGE_PIN AU19 [get_ports WDOG_RREQ]

# native DDR pin names

# set_property PACKAGE_PIN A17 [get_ports {c0_ddr4_dq[37]}]
# set_property PACKAGE_PIN F24 [get_ports {c0_ddr4_dq[54]}]
# set_property PACKAGE_PIN F23 [get_ports {c0_ddr4_dq[55]}]
# set_property PACKAGE_PIN B15 [get_ports {c0_ddr4_dq[28]}]
# set_property PACKAGE_PIN D23 [get_ports {c0_ddr4_dq[52]}]
# set_property PACKAGE_PIN D24 [get_ports {c0_ddr4_dq[53]}]
# set_property PACKAGE_PIN C24 [get_ports {c0_ddr4_dm_dbi_n[5]}]
# set_property PACKAGE_PIN A22 [get_ports {c0_ddr4_dq[46]}]
# set_property PACKAGE_PIN A23 [get_ports {c0_ddr4_dq[47]}]
# set_property PACKAGE_PIN C13 [get_ports {c0_ddr4_dq[29]}]
# set_property PACKAGE_PIN A14 [get_ports {c0_ddr4_dq[27]}]
# set_property PACKAGE_PIN E22 [get_ports {c0_ddr4_dqs_t[6]}]
# set_property PACKAGE_PIN E21 [get_ports {c0_ddr4_dqs_c[6]}]
# set_property PACKAGE_PIN G22 [get_ports {c0_ddr4_dq[50]}]
# set_property PACKAGE_PIN G21 [get_ports {c0_ddr4_dq[51]}]
# set_property PACKAGE_PIN H24 [get_ports {c0_ddr4_dm_dbi_n[6]}]
# set_property PACKAGE_PIN A24 [get_ports {c0_ddr4_dq[42]}]
# set_property PACKAGE_PIN B22 [get_ports {c0_ddr4_dqs_t[5]}]
# set_property PACKAGE_PIN B21 [get_ports {c0_ddr4_dqs_c[5]}]
# set_property PACKAGE_PIN B17 [get_ports {c0_ddr4_dqs_t[4]}]
# set_property PACKAGE_PIN B16 [get_ports {c0_ddr4_dqs_c[4]}]
# set_property PACKAGE_PIN A18 [get_ports {c0_ddr4_dq[38]}]
# set_property PACKAGE_PIN A12 [get_ports {c0_ddr4_dq[31]}]
# set_property PACKAGE_PIN D25 [get_ports {c0_ddr4_dq[48]}]
# set_property PACKAGE_PIN E23 [get_ports {c0_ddr4_dq[49]}]
# set_property PACKAGE_PIN C23 [get_ports {c0_ddr4_dq[40]}]
# set_property PACKAGE_PIN A25 [get_ports {c0_ddr4_dq[43]}]
# set_property PACKAGE_PIN C22 [get_ports {c0_ddr4_dq[44]}]
# set_property PACKAGE_PIN B14 [get_ports {c0_ddr4_dq[24]}]
# set_property PACKAGE_PIN K18 [get_ports {c0_ddr4_adr[4]}]
# set_property PACKAGE_PIN C21 [get_ports {c0_ddr4_dq[41]}]
# set_property PACKAGE_PIN D21 [get_ports {c0_ddr4_dq[45]}]
# set_property PACKAGE_PIN C16 [get_ports {c0_ddr4_dq[32]}]
# set_property PACKAGE_PIN E12 [get_ports {c0_ddr4_dq[16]}]
# set_property PACKAGE_PIN D13 [get_ports {c0_ddr4_dq[25]}]
# set_property PACKAGE_PIN C12 [get_ports {c0_ddr4_dqs_t[3]}]
# set_property PACKAGE_PIN B12 [get_ports {c0_ddr4_dqs_c[3]}]
# set_property PACKAGE_PIN E15 [get_ports {c0_ddr4_dq[18]}]
# #set_property PACKAGE_PIN P18 [get_ports {c0_ddr4_ck_t[1]}]
# #set_property PACKAGE_PIN N18 [get_ports {c0_ddr4_ck_c[1]}]
# set_property PACKAGE_PIN L19 [get_ports {c0_ddr4_adr[0]}]
# set_property PACKAGE_PIN J18 [get_ports {c0_ddr4_adr[5]}]
# #set_property PACKAGE_PIN E20 [get_ports {c0_ddr4_cke[0]}]
# set_property PACKAGE_PIN E20 [get_ports {c0_ddr4_cke}]
# set_property PACKAGE_PIN D19 [get_ports c0_ddr4_act_n]
# set_property PACKAGE_PIN F12 [get_ports {c0_ddr4_dq[17]}]
# set_property PACKAGE_PIN F15 [get_ports {c0_ddr4_dq[19]}]
# set_property PACKAGE_PIN L18 [get_ports {c0_ddr4_adr[2]}]
# set_property PACKAGE_PIN K16 [get_ports {c0_ddr4_adr[3]}]
# set_property PACKAGE_PIN J16 [get_ports {c0_ddr4_adr[1]}]
# #set_property PACKAGE_PIN E17 [get_ports {c0_ddr4_cke[1]}]
# set_property PACKAGE_PIN E18 [get_ports c0_ddr4_reset_n]
# set_property PACKAGE_PIN F14 [get_ports {c0_ddr4_dqs_t[2]}]
# set_property PACKAGE_PIN F13 [get_ports {c0_ddr4_dqs_c[2]}]
# #set_property PACKAGE_PIN P16 [get_ports {c0_ddr4_ck_t[0]}]
# set_property PACKAGE_PIN P16 [get_ports {c0_ddr4_ck_t}]
# #set_property PACKAGE_PIN N16 [get_ports {c0_ddr4_ck_c[0]}]
# set_property PACKAGE_PIN N16 [get_ports {c0_ddr4_ck_c}]
# set_property PACKAGE_PIN F19 [get_ports {c0_ddr4_bg[0]}]
# #set_property PACKAGE_PIN F18 [get_ports {c0_ddr4_bg[1]}]
# #set_property PACKAGE_PIN E16 [get_ports {c0_ddr4_odt[0]}]
# set_property PACKAGE_PIN E16 [get_ports {c0_ddr4_odt}]
# #set_property PACKAGE_PIN F17 [get_ports {c0_ddr4_cs_n[0]}]
# set_property PACKAGE_PIN F17 [get_ports {c0_ddr4_cs_n}]
# #set_property PACKAGE_PIN F20 [get_ports {c0_ddr4_cs_n[1]}]
# #set_property PACKAGE_PIN D20 [get_ports {c0_ddr4_odt[1]}]
# set_property PACKAGE_PIN K13 [get_ports {c0_ddr4_dq[10]}]
# set_property PACKAGE_PIN J14 [get_ports {c0_ddr4_dq[11]}]
# set_property PACKAGE_PIN H17 [get_ports {c0_ddr4_adr[16]}]
# set_property PACKAGE_PIN G17 [get_ports {c0_ddr4_ba[0]}]
# set_property PACKAGE_PIN H16 [get_ports {c0_ddr4_adr[14]}]
# set_property PACKAGE_PIN G19 [get_ports {c0_ddr4_ba[1]}]
# set_property PACKAGE_PIN N11 [get_ports {c0_ddr4_dqs_t[0]}]
# set_property PACKAGE_PIN M11 [get_ports {c0_ddr4_dqs_c[0]}]
# set_property PACKAGE_PIN J15 [get_ports {c0_ddr4_dq[8]}]
# set_property PACKAGE_PIN K15 [get_ports {c0_ddr4_dq[9]}]
# set_property PACKAGE_PIN G16 [get_ports {c0_ddr4_adr[15]}]
# set_property PACKAGE_PIN M10 [get_ports {c0_ddr4_dq[6]}]
# set_property PACKAGE_PIN L10 [get_ports {c0_ddr4_dq[7]}]
# set_property PACKAGE_PIN J11 [get_ports {c0_ddr4_dqs_t[1]}]
# set_property PACKAGE_PIN J10 [get_ports {c0_ddr4_dqs_c[1]}]
# set_property PACKAGE_PIN L17 [get_ports {c0_ddr4_adr[6]}]
# set_property PACKAGE_PIN K17 [get_ports {c0_ddr4_adr[8]}]
# set_property PACKAGE_PIN M17 [get_ports {c0_ddr4_adr[9]}]
# set_property PACKAGE_PIN M16 [get_ports {c0_ddr4_adr[7]}]
# set_property PACKAGE_PIN M19 [get_ports {c0_ddr4_adr[10]}]
# set_property PACKAGE_PIN M15 [get_ports {c0_ddr4_adr[11]}]
# set_property PACKAGE_PIN N17 [get_ports {c0_ddr4_adr[12]}]
# set_property PACKAGE_PIN N19 [get_ports {c0_ddr4_adr[13]}]
# set_property PACKAGE_PIN L22 [get_ports {c0_ddr4_dm_dbi_n[7]}]
# set_property PACKAGE_PIN P11 [get_ports {c0_ddr4_dq[0]}]
# set_property PACKAGE_PIN P10 [get_ports {c0_ddr4_dq[1]}]
# set_property PACKAGE_PIN L12 [get_ports {c0_ddr4_dq[2]}]
# set_property PACKAGE_PIN M12 [get_ports {c0_ddr4_dq[3]}]
# set_property PACKAGE_PIN N13 [get_ports {c0_ddr4_dq[4]}]
# set_property PACKAGE_PIN N12 [get_ports {c0_ddr4_dq[5]}]
# set_property PACKAGE_PIN K11 [get_ports {c0_ddr4_dq[12]}]
# set_property PACKAGE_PIN K10 [get_ports {c0_ddr4_dq[13]}]
# set_property PACKAGE_PIN J13 [get_ports {c0_ddr4_dq[14]}]
# set_property PACKAGE_PIN K12 [get_ports {c0_ddr4_dq[15]}]
# set_property PACKAGE_PIN H12 [get_ports {c0_ddr4_dq[20]}]
# set_property PACKAGE_PIN G12 [get_ports {c0_ddr4_dq[21]}]
# set_property PACKAGE_PIN G15 [get_ports {c0_ddr4_dq[22]}]
# set_property PACKAGE_PIN G14 [get_ports {c0_ddr4_dq[23]}]
# set_property PACKAGE_PIN A13 [get_ports {c0_ddr4_dq[26]}]
# set_property PACKAGE_PIN A15 [get_ports {c0_ddr4_dq[30]}]
# set_property PACKAGE_PIN C19 [get_ports {c0_ddr4_dq[33]}]
# set_property PACKAGE_PIN B19 [get_ports {c0_ddr4_dq[34]}]
# set_property PACKAGE_PIN A20 [get_ports {c0_ddr4_dq[35]}]
# set_property PACKAGE_PIN D16 [get_ports {c0_ddr4_dq[36]}]
# set_property PACKAGE_PIN A19 [get_ports {c0_ddr4_dq[39]}]
# set_property PACKAGE_PIN H22 [get_ports {c0_ddr4_dq[56]}]
# set_property PACKAGE_PIN J23 [get_ports {c0_ddr4_dq[57]}]
# set_property PACKAGE_PIN K20 [get_ports {c0_ddr4_dq[58]}]
# set_property PACKAGE_PIN L20 [get_ports {c0_ddr4_dq[59]}]
# set_property PACKAGE_PIN H21 [get_ports {c0_ddr4_dq[60]}]
# set_property PACKAGE_PIN H23 [get_ports {c0_ddr4_dq[61]}]
# set_property PACKAGE_PIN K23 [get_ports {c0_ddr4_dq[62]}]
# set_property PACKAGE_PIN J21 [get_ports {c0_ddr4_dq[63]}]
# set_property PACKAGE_PIN N14 [get_ports {c0_ddr4_dm_dbi_n[0]}]
# set_property PACKAGE_PIN L14 [get_ports {c0_ddr4_dm_dbi_n[1]}]
# set_property PACKAGE_PIN H14 [get_ports {c0_ddr4_dm_dbi_n[2]}]
# set_property PACKAGE_PIN D14 [get_ports {c0_ddr4_dm_dbi_n[3]}]
# set_property PACKAGE_PIN C18 [get_ports {c0_ddr4_dm_dbi_n[4]}]
# set_property PACKAGE_PIN K21 [get_ports {c0_ddr4_dqs_t[7]}]

#set_property CFGBVS GND [current_design]
#set_property CONFIG_VOLTAGE 1.8 [current_design]

# set_property PACKAGE_PIN H19 [get_ports c0_sys_clk_p]
# set_property PACKAGE_PIN H18 [get_ports c0_sys_clk_n]

# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports SATA_CLK_N]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports SATA_CLK_P]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports GTX_CLK_N]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports GTX_CLK_P]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_M2C_P[1]}]
# set_property IOSTANDARD DIFF_HSTL_I_18 [get_ports {CLK_M2C_P[0]}]

# set_property PACKAGE_PIN AB31 [get_ports GTX_CLK_P]
# set_property PACKAGE_PIN AB32 [get_ports GTX_CLK_N]

# set_property PACKAGE_PIN AH39 [get_ports {DP_C2M_N[0]}]
# set_property PACKAGE_PIN AF39 [get_ports {DP_C2M_N[1]}]
# set_property PACKAGE_PIN AD39 [get_ports {DP_C2M_N[2]}]
# set_property PACKAGE_PIN AB39 [get_ports {DP_C2M_N[3]}]
# set_property PACKAGE_PIN Y39 [get_ports {DP_C2M_N[4]}]
# set_property PACKAGE_PIN V39 [get_ports {DP_C2M_N[5]}]
# set_property PACKAGE_PIN K39 [get_ports {DP_C2M_N[6]}]
# set_property PACKAGE_PIN M39 [get_ports {DP_C2M_N[7]}]
# set_property PACKAGE_PIN P39 [get_ports {DP_C2M_N[8]}]
# set_property PACKAGE_PIN T39 [get_ports {DP_C2M_N[9]}]
# set_property PACKAGE_PIN AH38 [get_ports {DP_C2M_P[0]}]
# set_property PACKAGE_PIN AF38 [get_ports {DP_C2M_P[1]}]
# set_property PACKAGE_PIN AD38 [get_ports {DP_C2M_P[2]}]
# set_property PACKAGE_PIN AB38 [get_ports {DP_C2M_P[3]}]
# set_property PACKAGE_PIN Y38 [get_ports {DP_C2M_P[4]}]
# set_property PACKAGE_PIN V38 [get_ports {DP_C2M_P[5]}]
# set_property PACKAGE_PIN K38 [get_ports {DP_C2M_P[6]}]
# set_property PACKAGE_PIN M38 [get_ports {DP_C2M_P[7]}]
# set_property PACKAGE_PIN P38 [get_ports {DP_C2M_P[8]}]
# set_property PACKAGE_PIN T38 [get_ports {DP_C2M_P[9]}]
# set_property PACKAGE_PIN AE36 [get_ports {GBTCLK_M2C_P[0]}]
# set_property PACKAGE_PIN AE37 [get_ports {GBTCLK_M2C_N[0]}]
# set_property PACKAGE_PIN AA36 [get_ports {GBTCLK_M2C_P[1]}]
# set_property PACKAGE_PIN AA37 [get_ports {GBTCLK_M2C_N[1]}]

# create_clock -period 15.515 -name clk_mgtrefclk0_x0y4_p [get_ports {GBTCLK_M2C_P[0]}]
# create_clock -period 15.515 -name clk_mgtrefclk0_x0y7_p [get_ports {GBTCLK_M2C_P[1]}]

# # False path constraints
# # ----------------------------------------------------------------------------------------------------------------------
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *bit_synchronizer*inst/i_in_meta_reg}]
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *reset_synchronizer*inst/rst_in_*_reg}]
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_tx_inst/*gtwiz_userclk_tx_active_*_reg}]
# set_false_path -to [get_cells -hierarchical -filter {NAME =~ *gtwiz_userclk_rx_inst/*gtwiz_userclk_rx_active_*_reg}]

#set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets iACLK]
#set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CFG_CLK_IBUF_inst/O]
# set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets iGPUCLK]
# set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets iMCLK]

set_property PULLUP true [get_ports QSPI_D0]
set_property PULLUP true [get_ports QSPI_D1]
set_property PULLUP true [get_ports QSPI_D2]
set_property PULLUP true [get_ports QSPI_D3]

# set_property IOSTANDARD SSTL12_DCI [get_ports "c0_ddr4_bg[0]"]
# set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports "c0_ddr4_bg[0]"]

set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property BITSTREAM.CONFIG.UNUSEDPIN Pullnone [current_design]
set_property BITSTREAM.CONFIG.PERSIST Yes [current_design]
set_property BITSTREAM.STARTUP.MATCH_CYCLE Auto [current_design]
set_property BITSTREAM.GENERAL.COMPRESS True [current_design]
set_property CONFIG_MODE S_SELECTMAP [current_design]


