// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define XIOT_RQ1 0
#define XIOT_RQ2 1
#define XIOT_ACK 2
#define XIOT_DATA 3
#define XIOT_DATAWIDTH 4

// ------- //
// XIOTsm0 //
// ------- //

#define XIOTsm0_wrap_target 0
#define XIOTsm0_wrap 26

static const uint16_t XIOTsm0_program_instructions[] = {
            //     .wrap_target
    0xe02f, //  0: set    x, 15                      
    0xe08f, //  1: set    pindirs, 15                
    0x8080, //  2: pull   noblock                    
    0xa027, //  3: mov    x, osr                     
    0x6004, //  4: out    pins, 4                    
    0x10c7, //  5: jmp    pin, 7          side 0     
    0x0002, //  6: jmp    2                          
    0xf980, //  7: set    pindirs, 0      side 1 [1] 
    0x2281, //  8: wait   1 gpio, 1              [2] 
    0x4004, //  9: in     pins, 4                    
    0xb0e6, // 10: mov    osr, isr        side 0     
    0x6041, // 11: out    y, 1                       
    0x6021, // 12: out    x, 1                       
    0x2001, // 13: wait   0 gpio, 1                  
    0x0074, // 14: jmp    !y, 20                     
    0xe08f, // 15: set    pindirs, 15                
    0x0053, // 16: jmp    x--, 19                    
    0xc205, // 17: irq    nowait 5               [2] 
    0x0014, // 18: jmp    20                         
    0xc207, // 19: irq    nowait 7               [2] 
    0xa342, // 20: nop                           [3] 
    0x4004, // 21: in     pins, 4                    
    0x3b81, // 22: wait   1 gpio, 1       side 1 [3] 
    0x4004, // 23: in     pins, 4                    
    0x3001, // 24: wait   0 gpio, 1       side 0     
    0x3800, // 25: wait   0 gpio, 0       side 1     
    0xc000, // 26: irq    nowait 0                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program XIOTsm0_program = {
    .instructions = XIOTsm0_program_instructions,
    .length = 27,
    .origin = -1,
};

static inline pio_sm_config XIOTsm0_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + XIOTsm0_wrap_target, offset + XIOTsm0_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}
#endif

// -------- //
// XIOTsm13 //
// -------- //

#define XIOTsm13_wrap_target 0
#define XIOTsm13_wrap 4

static const uint16_t XIOTsm13_program_instructions[] = {
            //     .wrap_target
    0x20d4, //  0: wait   1 irq, 4 rel               
    0x8080, //  1: pull   noblock                    
    0x7804, //  2: out    pins, 4         side 1     
    0x2081, //  3: wait   1 gpio, 1                  
    0x7004, //  4: out    pins, 4         side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program XIOTsm13_program = {
    .instructions = XIOTsm13_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config XIOTsm13_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + XIOTsm13_wrap_target, offset + XIOTsm13_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void XIOT0_program_init(PIO pio) {
    pio_sm_config cfg_sm0 = XIOT_pio_get_default_sm_config();
    pio_sm_config cfg_sm1 = XIOT_pio_get_default_sm_config();
    pio_sm_config cfg_sm3 = XIOT_pio_get_default_sm_config();
// SM0: status, command parse and set direction, Mon/RX0
    sm_config_set_in_shift(&cfg_sm0, false, true, 12); // SHL, Autopush
    sm_config_set_out_shift(&cfg_sm0, true, false, 4); // SHR, no autopull, 4 bits of status flags
    sm_config_set_in_pins(&cfg_sm0, XIOT_DATA);
    sm_config_set_out_pins(&cfg_sm0, XIOT_DATA, XIOT_DATAWIDTH);
    sm_config_set_sideset_pins(&cfg_sm0, XIOT_ACK);
    sm_config_set_sideset(&cfg_sm0, 1, true);
    sm_config_set_jmp_pin(&cfg_sm0, XIOT_RQ1);  //
    sm_config_set_wrap(&cfg_sm0, XIOTsm0_wrap_target, XIOTsm0_wrap); // wrap from 0
// SM1: TX1, data transfer interrupt thread
    sm_config_set_out_shift(&cfg_sm1, true, false, 8); // SHR, no autopull, 8-bit data
    sm_config_set_out_pins(&cfg_sm1, XIOT_DATA, XIOT_DATAWIDTH);
    sm_config_set_sideset_pins(&cfg_sm1, XIOT_ACK);
    sm_config_set_sideset(&cfg_sm1, 1, true);
    sm_config_set_wrap(&cfg_sm1, XIOTsm13_wrap_target, XIOTsm13_wrap);
// SM3: TX3, data transfer interrupt thread
    sm_config_set_out_shift(&cfg_sm3, true, false, 8); // SHR, no autopull, 8-bit data
    sm_config_set_out_pins(&cfg_sm3, XIOT_DATA, XIOT_DATAWIDTH);
    sm_config_set_sideset_pins(&cfg_sm3, XIOT_ACK);
    sm_config_set_sideset(&cfg_sm3, 1, true);
    sm_config_set_wrap(&cfg_sm3, XIOTsm13_wrap_target, XIOTsm13_wrap);
    // Map the state machine's data pins
    // parameter to this function.
    pio_gpio_init(pio, XIOT_ACK, true);
    // Connext PIO data bus (connect PIO to the pad)
    pio_gpio_init(pio, XIOT_DATA+0);
    pio_gpio_init(pio, XIOT_DATA+1);
    pio_gpio_init(pio, XIOT_DATA+2);
    pio_gpio_init(pio, XIOT_DATA+3);
    // Set the pin direction to input at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, XIOT_DATA, XIOT_DATAWIDTH, true);
    pio_sm_set_consecutive_pindirs(pio, sm, XIOT_ACK, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_add_program(pio, pio_program_t *(XIOTsm0_program))
    pio_sm_init(pio, 0, 0, &cfg_sm0);
    pio_add_program(pio, pio_program_t *(XIOTsm13_program))
    pio_sm_init(pio, 1, XIOTsm13_wrap_target, &cfg_sm1);
    pio_sm_init(pio, 3, XIOTsm13_wrap_target, &cfg_sm3);
   // Set the state machines running (1,3 at WFI, then SM0 controller)
    pio_sm_set_enabled(pio, 1, true);
    pio_sm_set_enabled(pio, 3, true);
    pio_sm_set_enabled(pio, 0, true);
}


#endif
