# System Paths, please edit for your system
set io_lib_dir /home/dwn1c21/SoC-Labs/phys_ip/TSMC/65/CMOS/LP/IO2.5V/iolib/linear/tpdn65lpnv2od3_200a_FE/TSMCHOME/digital/Front_End/timing_power_noise/NLDM/tpdn65lpnv2od3_200a/
set sc_lib_dir $::env(PHYS_IP)/arm/tsmc/cln65lp/sc12_base_rvt/r0p0/lib/ 
set pmk_lib_dir $::env(PHYS_IP)/arm/tsmc/cln65lp/sc12_pmk_rvt_hvt/r0p0/lib/

# Automatically setup !Don't touch!
set rf_16k_dir $::env(SOCLABS_PROJECT_DIR)/memories/rf_16k/ 
set rf_08k_dir $::env(SOCLABS_PROJECT_DIR)/memories/rf_08k/ 
set bootrom_dir $::env(SOCLABS_PROJECT_DIR)/memories/bootrom/

set lib_search_path_list "$io_lib_dir $sc_lib_dir $pmk_lib_dir $rf_16k_dir $rf_08k_dir $bootrom_dir"

set BASE_LIB sc12_cln65lp_base_rvt_ss_typical_max_1p08v_125c.lib
set PMK_LIB sc12_cln65lp_pmk_rvt_hvt_ss_typical_max_1p08v_125c.lib
set PMK_CROSS_LIB sc12_cln65lp_pmk_rvt_hvt_ss_typical_max_1p08v_1p08v_125c.lib
set RF_LIB rf_16k_ss_1p08v_1p08v_125c.lib
set RF_08K rf_08k_ss_1p08v_1p08v_125c.lib
set ROM_LIB rom_via_ss_1p08v_1p08v_125c.lib
set IO_PAD_DRIVER tpdn65lpnv2od3bc.lib

set syn_lib_list [list $BASE_LIB $PMK_LIB $PMK_CROSS_LIB $RF_LIB $RF_08K $ROM_LIB $IO_PAD_DRIVER]

set block_name nanosoc_chip_pads

set LOG_DIR ../logs
set REPORT_DIR ../reports
set OUT_DIR ../outputs

set hdl_file_list $::env(SOCLABS_PROJECT_DIR)/imp/ASIC/nanosoc/flist/genus_flist.tcl
set top_level_hdl $::env(SOCLABS_NANOSOC_TECH_DIR)/ASIC/nanosoc_chip_pads/tsmc65lp/nanosoc_chip_pads_44pin.v

set constraints_file ../inputs/constraints.sdc

set DFT 1

set power_nets {VDD VDDACC VDDIO}
set ground_nets {VSS VSSIO}


# Set library paths 
# !! EDIT THIS TO YOUR PATHS IN YOUR ENVIRONMENT
set TECH_LEF /home/dwn1c21/SoC-Labs/util/PRTF_EDI_65nm_001_Cad_V24a/PRTF_EDI_N65_9M_6X1Z1U_RDL.24a.tlef
#$::env(PHYS_IP)/arm/tsmc/cln65lp/arm_tech/r2p0/lef/1p9m_6x2z/sc12_tech.lef
set BASE_LEF $::env(PHYS_IP)/arm/tsmc/cln65lp/sc12_base_rvt/r0p0/lef/sc12_cln65lp_base_rvt.lef
set IO_PAD_LEF /home/dwn1c21/SoC-Labs/phys_ip/TSMC/65/iolib/tpbn65v_200b_FE/TSMCHOME/digital/Back_End/lef/tpbn65v_200b/cup/9m/9M_6X1Z1U/lef/tpbn65v_9lm.lef
set IO_PAD_DRIVER_LEF /home/dwn1c21/SoC-Labs/phys_ip/TSMC/65/CMOS/LP/IO2.5V/iolib/linear/tpdn65lpnv2od3_200a_FE/TSMCHOME/digital/Back_End/lef/tpdn65lpnv2od3_140b/mt_2/9lm/lef/tpdn65lpnv2od3_9lm.lef
set PMK_LEF $::env(PHYS_IP)/arm/tsmc/cln65lp/sc12_pmk_rvt_hvt/r0p0/lef/sc12_cln65lp_pmk_rvt_hvt.lef

# !! THESE SHOULD BE CORRECT FOR ANY ENVIRONMENT AS THEY ARE GENERATED BY MAKEFILE
set RF_LEF $::env(SOCLABS_PROJECT_DIR)/memories/rf_16k/rf_16k.lef
set RF_08K_LEF $::env(SOCLABS_PROJECT_DIR)/memories/rf_08k/rf_08k.lef
set ROM_LEF $::env(SOCLABS_PROJECT_DIR)/memories/bootrom/rom_via.lef


set lef_file_list [list ${TECH_LEF} ${BASE_LEF} ${PMK_LEF} ${IO_PAD_LEF} ${IO_PAD_DRIVER_LEF} ${RF_LEF} ${RF_08K_LEF} ${ROM_LEF}]

set process_node 65

