#----------------------------------------------------------------------------
# The confidential and proprietary information contained in this file may
# only be used by a person authorised under and to the extent permitted
# by a subsisting licensing agreement from Arm Limited or its affiliates.
#
# (C) COPYRIGHT 2021-2022 Arm Limited or its affiliates.
# ALL RIGHTS RESERVED
#
# This entire notice must be reproduced on all copies of this file
# and copies of this file may only be made by a person if such person is
# permitted to do so under the terms of a subsisting license agreement
# from Arm Limited or its affiliates.
#----------------------------------------------------------------------------
#
# Release Information : DMA350-r0p0-00rel0
#
# -----------------------------------------------------------------------------
#  Abstract : User Configuration file for ADA DMA
# -----------------------------------------------------------------------------

#
# CONFIG_NAME: Name of the configuration.
#     Each unifiqued element and top is suffixed with
#     _${CONFIG_NAME}
#
CONFIG_NAME: sldma350

#
# ADDR_WIDTH: Address Bus width
#
#     Valid values:
#         32-64
ADDR_WIDTH: 32

#
# DATA_WIDTH: Data Bus width
#
#     Valid values:
#         [32,64,128]
DATA_WIDTH: 32

#
# CHID_WIDTH: Width of the configurable channel ID user signal.
#     When set to 0, then the archid and awchid ports are not present on the module.
#
#     Valid values:
#         0-16
CHID_WIDTH: 0

#
# GPO_WIDTH: Width of GPO output for every channel. When multiple channels have GPOs
#     then the width must be set to the maximum number of GPOs a channel can have,
#     and unused GPO ports need to be left unconnected. When all bits of CH_GPO_MASK
#     is 0, this parameter is not relevant.
#
#     Valid values:
#         1-32
GPO_WIDTH: 0

#
# CH_GPO_MASK: A bitmask for enabling the GPO port for each channel. The width of the
#     bitmask is NUM_CHANNELS-1. When bit n is set to 1 then the GPO is enabled for
#     channel n and the gpo_ch_n[GPO_WIDTH-1:0] port appears on the module.
#
#     Valid values:
#         0-(2^NUM_CHANNELS-1)
CH_GPO_MASK: 0x0

#
# CH_STREAM_MASK: A bitmask for enabling the stream interfaces for each channel.
#     The width of the bitmask is NUM_CHANNELS-1. When bit n is set to 1 then
#     the stream interfaces are enabled for channel n and the relevant ports
#     appears on the module. NOTE: When streaming interface is enabled the actual
#     FIFO size of the channel will be the double of CH_<N>_FIFO_DEPTH
#
#     Valid values:
#         0-(2^NUM_CHANNELS-1)
CH_STREAM_MASK: 0x3

#
# CH_<N>_FIFO_DEPTH: Sets the FIFO depth for channel <N> that defines the number of
#     DATA_WIDTH size entries a channel can hold for a transfer. N goes from 0 to
#     NUM_CHANNELS-1. In combination with the TRANSIZE setting of the command, the
#     FIFO depth defines the maximum burst size a channel can support. This setting
#     needs to be aligned with the bandwidth requirements of the channel but it
#     highly affects the area of the design.
#
#     Valid values:
#         [1,2,4,8,16,32,64]
CH_0_FIFO_DEPTH: 32
CH_1_FIFO_DEPTH: 32

#
# CH_EXT_FEAT_MASK: A bitmask for enabling the extended feature set for each channel.
#     The extension contains 2D, WRAP, TMPLT features. Default value enables it for
#     the number of channels.
#
#     Valid values:
#         0-(2^NUM_CHANNELS-1)
CH_EXT_FEAT_MASK: 0x3

#
# NUM_CHANNELS: Number of configurable DMA channels.
#
#     Valid values:
#         1-8
NUM_CHANNELS: 2

#
# NUM_TRIGGER_IN: Number of trigger input ports.
#
#     Valid values:
#         0-32
NUM_TRIGGER_IN: 2

#
# NUM_TRIGGER_OUT: Number of trigger output ports.
#
#     Valid values:
#         0-32
NUM_TRIGGER_OUT: 0

#
# TRIG_IN_SYNC_EN_MASK: A bitmask for enabling the synchronizers on the trigger in
#     interfaces for each trigger port. The width of the bitmask is NUM_TRIGGER_IN-1.
#     When bit n is set to 1 then the trigger in interface is considered asynchronous
#     and the synchronizer logic is placed on the selected input ports.
#
#     Valid values:
#         0-(2^NUM_TRIGGER_IN-1)
TRIG_IN_SYNC_EN_MASK: 0x0

#
# TRIG_OUT_SYNC_EN_MASK: A bitmask for enabling the synchronizers on the trigger out
#     interfaces for each trigger port. The width of the bitmask is NUM_TRIGGER_OUT-1.
#     When bit n is set to 1 then the trigger out interface is considered asynchronous
#     and the synchronizer logic is placed on the selected input ports.
#
#     Valid values:
#         0-(2^NUM_TRIGGER_OUT-1)
TRIG_OUT_SYNC_EN_MASK: 0x0

#
# AXI5_M1_PRESENT: Enables an additional master port. When set the m1 master port is
#     present on the top level port list and additional include file can be used with
#     a System Verilog function that defines which address ranges are mapped to the m1
#     interface.
#
#     Valid values:
#         [0,1]
AXI5_M1_PRESENT: 1

#
# SECEXT_PRESENT: Enables TrustZone security support.
#
#     Valid values:
#         [0,1]
SECEXT_PRESENT: 0

#
# AXI5_M1_ADDR_MAP: Select AXI M1 master.
#
#     Valid values:
#         relative path to logical
AXI5_M1_ADDR_MAP: models/modules/generic/address_map_m1_nanosoc.sv
