###############################################################
#  Generated by:      Cadence Innovus 21.11-s130_1
#  OS:                Linux x86_64(Host ID srv03335)
#  Generated on:      Thu Nov 16 16:18:31 2023
#  Design:            nanosoc_chip_pads
#  Command:           write_io_file -locations -template nanosoc_chip_pads.save.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopad
	(topleft
		(inst name="CornerCell1" cell=gf180mcu_fd_io__cor)
	)
    (top
	(inst  name="uPAD_TEST_I"	offset=500		)
	(inst  name="uPAD_SWDCK_I"		)
	(inst  name="uPAD_VDD_3"		)
	(inst  name="uPAD_VSS_3"		)
	(inst  name="uPAD_VDDIO_3"		)
	(inst  name="uPAD_P1_00"		)
	(inst  name="uPAD_P1_01"	offset=4425	)
    )
	(topright
		(inst name="CornerCell2" cell=gf180mcu_fd_io__cor)
	)
    (left
	(inst  name="uPAD_P0_04"	offset=500)
	(inst  name="uPAD_P0_05"	)
	(inst  name="uPAD_P0_03"	)
	(inst  name="uPAD_VDDACC_0"	)
	(inst  name="uPAD_VSS_0"	)
	(inst  name="uPAD_CLK_I"	)
	(inst  name="uPAD_VDD_0"	)
	(inst  name="uPAD_VDDIO_0"	)
	(inst  name="uPAD_SWDIO_IO"	)
	(inst  name="uPAD_VSSIO_0"	)
	(inst  name="uPAD_P0_06"	)
	(inst  name="uPAD_P0_07"	offset=4425	)
    )
	(bottomleft
		(inst name="CornerCell3" cell=gf180mcu_fd_io__cor)
	)
    (bottom
	(inst  name="uPAD_P0_02" offset=500	)
	(inst  name="uPAD_VDDACC_1"	)
	(inst  name="uPAD_SE_I"		)
	(inst  name="uPAD_VDD_1"	)
	(inst  name="uPAD_VSS_1"	)
	(inst  name="uPAD_P0_01"	)
	(inst  name="uPAD_P0_00"	offset=4425	)
    )
	(bottomright
		(inst name="CornerCell4" cell=gf180mcu_fd_io__cor)
	)
    (right
	(inst  name="uPAD_P1_07"  offset=500)
	(inst  name="uPAD_P1_06"	)
	(inst  name="uPAD_VSSIO_1"	)
	(inst  name="uPAD_P1_03"	)
	(inst  name="uPAD_P1_02"	)
	(inst  name="uPAD_VDDACC_2"	)
	(inst  name="uPAD_VDD_2"	)
	(inst  name="uPAD_VSS_2"	)
	(inst  name="uPAD_VDDIO_2"	)
	(inst  name="uPAD_NRST_I"	)
	(inst  name="uPAD_P1_04"	)
	(inst  name="uPAD_P1_05"	offset=4425	)
    )
)
