# user spec file, compiler rom_via_hdd_rvt_rvt, version r0p0

activity_factor = 5
back_biasing = off
bits = 32
bmux = on
bus_notation = on
check_instname = on
code_file = $SOCLABS_NANOSOC_TECH_DIR/testcodes/bootloader/bootloader.bin
corners = ff_1p32v_1p32v_125c,ff_1p32v_1p32v_m40c,ss_1p08v_1p08v_125c,ss_1p08v_1p08v_m40c,tt_1p20v_1p20v_25c
cust_comment = 
diodes = on
drive = 6
ema = on
frequency = 250.0
instname = rom_via
left_bus_delim = [
libertyviewstyle = nldm
libname = USERLIB
mode = random
mux = 8
mvt = 
name_case = upper
power_gating = on
power_type = otc
prefix = 
pwr_gnd_rename = vdde:VDDE,vsse:VSSE
right_bus_delim = ]
site_def = off
top_layer = m5-m10
words = 256
