# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
XIOT_RQ1 = 0
XIOT_RQ2 = 1
XIOT_ACK = 2
XIOT_DATA = 3
XIOT_DATAWIDTH = 4

# ------- #
# XIOTsm0 #
# ------- #

@rp2.asm_pio(out_init=(rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH), set_init=(rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH), sideset_init=(rp2.PIO.OUT_HIGH), out_shiftdir=rp2.PIO.SHIFT_RIGHT, in_shiftdir=rp2.PIO.SHIFT_LEFT, autopush=True, autopull=False, push_thresh=12, pull_thresh=4)
def XIOTsm0():
    wrap_target()
    set(x, 15)                            # 0
    set(pindirs, 15)                      # 1
    label("2")
    pull(noblock)                         # 2
    mov(x, osr)                           # 3
    out(pins, 4)                          # 4
    jmp(pin, "7")           .side(0)      # 5
    jmp("2")                              # 6
    label("7")
    set(pindirs, 0)         .side(1) [1]  # 7
    wait(1, gpio, 1)                 [2]  # 8
    in_(pins, 4)                          # 9
    mov(osr, isr)           .side(0)      # 10
    out(y, 1)                             # 11
    out(x, 1)                             # 12
    wait(0, gpio, 1)                      # 13
    jmp(not_y, "20")                      # 14
    set(pindirs, 15)                      # 15
    jmp(x_dec, "19")                      # 16
    irq(nowait, 5)                   [2]  # 17
    jmp("20")                             # 18
    label("19")
    irq(nowait, 7)                   [2]  # 19
    label("20")
    nop()                            [3]  # 20
    in_(pins, 4)                          # 21
    wait(1, gpio, 1)        .side(1) [3]  # 22
    in_(pins, 4)                          # 23
    wait(0, gpio, 1)        .side(0)      # 24
    wait(0, gpio, 0)        .side(1)      # 25
    irq(nowait, 0)                        # 26
    wrap()


# -------- #
# XIOTsm13 #
# -------- #

@rp2.asm_pio(out_init=(rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH,rp2.PIO.OUT_HIGH), sideset_init=(rp2.PIO.OUT_HIGH), out_shiftdir=rp2.PIO.SHIFT_LEFT, autopull=True, pull_thresh=8)
def XIOTsm13():
    wrap_target()
    wait(1, irq, rel(4))                  # 0
    pull(noblock)                         # 1
    out(pins, 4)            .side(1)      # 2
    wait(1, gpio, 1)                      # 3
    out(pins, 4)            .side(0)      # 4
    wrap()



# 1 x controller state machine
## 3x target state machines
sm0 = rp2.StateMachine(0, XIOTsm0 , set_base=Pin(XIOT_DATA), out_base=Pin(XIOT_DATA), in_base=Pin(XIOT_DATA), sideset_base=XIOT_ACK, jmp_pin=XIOT_RQ1)
sm1 = rp2.StateMachine(1, XIOTsm13, out_base=Pin(XIOT_DATA), sideset_base=XIOT_ACK)
sm3 = rp2.StateMachine(3, XIOTsm13, out_base=Pin(XIOT_DATA), sideset_base=XIOT_ACK)
# global copy of virtual channel flags
xiot_vcflags = 0b1111
verbose = False
XIOT_MODE.value(0)
# Function to get target FIFO status
#From controller perspective:
#   FIFO_status[3:0] = { tx1, rx1, tx0, rx0}
#   Controller interprets as (tx1 empty, rx1_full, tx0 empty, rx0_full)
# so we need (rx)
#    fifo_status = rx1_not_empty << 3 | tx1_full << 2 | rx0_not_empty << 1 | tx0_full
def get_xiot_fifo_status():
    fifo_flags = 0b1111
    if sm0.rx_fifo() <= 1: #2 RX channels share SM0
        fifo_flags = fifo_flags & 0b0101
    if sm1.tx_fifo() > 0:
        fifo_flags = fifo_flags & 0b1110 #0b1110
    if sm3.tx_fifo() > 0:
        fifo_flags = fifo_flags & 0b1011 #0b1011
    return fifo_flags
# Function to update target FIFO status
def update_xiot_fifo_status():
    # global copy of virtual channel flags
    global xiot_vcflags
    xiot_vcflags = get_xiot_fifo_status()
    sm0.put(xiot_vcflags)
    return 
def xiot_xfer_poll():
    update_xiot_fifo_status()
    return(sm0.rx_fifo() > 0)
def xiot_xfer_change():
    update_xiot_fifo_status()
    return(sm0.rx_fifo() > 0)
def xiot_xfer_parse():
# sm0 returns 4-bit command + 8-bit data in 12 LSB
    rxd = sm0.get()
    chan1 = (rxd & 0x200) != 0
    read = (rxd & 0x100) == 0
    rxbyte = rxd & 0xff
    return(chan1, read, rxbyte)
# XIOT tx0->rx0 - SM1 FIFO/SM
# sm1 transfers byte data in bits[31:24]
def xiot_tx0(txbyte):  # host channel 0 tx
    sm1.put(txbyte<<24)
    return
def xiot_tx0_ready():
    return(sm1.tx_fifo() == 0) # <3
# XIOT tx1->rx1 - SM3 FIFO/SM
# sm3 transfers byte data in bits[31:24]
def xiot_tx1(txbyte):  # host channel 1 tx
    sm3.put(txbyte<<24)
    return
def xiot_tx1_ready():
    return(sm3.tx_fifo() == 0) # <3
def fifo_stats():
    print(sm0.tx_fifo(), sm1.tx_fifo(),  sm3.tx_fifo(),
          sm0.rx_fifo(), sm1.rx_fifo(),  sm3.rx_fifo(), end="\n")
def adp_console_enter():
    while True:
      if xiot_xfer_poll():
        break
    xiot_tx0(0x1b) # escape char
#def adp_upload():
# start both output state machines
sm1.active(1)
sm3.active(1)
sm0.put(0b1111) # all channels inactive
# finally start main read/control state machine
sm0.active(1)
adp_req = False
adp_mode = False
csvio_mode = False
get_xiot_fifo_status()
update_xiot_fifo_status()
verbose = True
### example main code usage
adp_console_enter()
adp_mode = True
# Loop indefinitely
while True:
# poll input RX FIFO
  while xiot_xfer_change() :
    chan1, read, rxbyte = xiot_xfer_parse()
    if (read and (chan1 == False)): # stdout channel
      sys.stdout.write(chr(rxbyte))
    if (read and (chan1 == True)) :  #data channel
      print("{",chr(rxbyte),"}",sep='',end='')
  if (not (adp_load and adp_mode)) and xiot_tx0_ready() and select.select([sys.stdin], [], [], 0)[0]:
    txbyte = sys.stdin.read(1) # Read just one character
    if txbyte == ']': # remap ']'
      xiot_tx0(0x1b) # to ESC // REPL issue
      adp_req = True
    else:
      xiot_tx0(ord(txbyte))
  if (adp_mode and adp_load) and xiot_tx0_ready() and (afile != 0) :
    txbyte = afile.read(1)  # Read just one character
    if txbyte == b'': # binary file end of file
      afile.close()
      afile = 0
      adp_load = 0
      csvio_mode = 1
      print("<csv file io starts...>")
    else:
      xiot_tx0(ord(txbyte))
  if csvio_mode and xiot_tx1_ready() and (sfile != 0):
    txbyte = sfile.read(1)  # Read exactly one character
    if not txbyte: # text file eof
      sfile.close()
      sfile = 0
      print("\n<csv file stim closed>")
    else:
      if verbose and (txbyte == (',')):
          print(",",end="")
      if verbose and (txbyte == ('\n')):
          print("\n",end="")
      xiot_tx1(ord(txbyte))

